// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CaliburnMicroTemplates
{
    internal sealed partial class Vsix
    {
        public const string Id = "CaliburnMicroTemplates.87aa90b8-9d1a-411e-a172-b277903a5b96";
        public const string Name = "CaliburnMicroTemplates";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "HP";
        public const string Tags = "";
    }
}
